version: '3.9'

services:
  db:
    image: postgres:13.3
    container_name: nheenote-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: nheenote
    ports:
      - 2003:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

